/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ec.mirian.gui.jframe;

import com.ec.mirian.internalFrame.IFactura;
import com.ec.mirian.internalFrame.IGuiaRemision;
import com.ec.mirian.internalFrame.Iconfiguracion;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author MARCELO
 */
public class Documentos extends javax.swing.JFrame {

    private static IFactura iFactura;
    private static IGuiaRemision iGuia;
    private static Iconfiguracion iconfiguracion;

    /**
     * Creates new form Documentos
     */
    public Documentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spPrincipal = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnFactura = new javax.swing.JButton();
        btnGuias = new javax.swing.JButton();
        BtnNotaCredito = new javax.swing.JButton();
        BtnNotaDebito = new javax.swing.JButton();
        BtnConfiguracion = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        destokp = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));

        btnFactura.setText("Factura");
        btnFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(btnFactura);

        btnGuias.setText("Guias");
        btnGuias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiasActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuias);

        BtnNotaCredito.setText("Nota Credito");
        jPanel1.add(BtnNotaCredito);

        BtnNotaDebito.setText("Nota Debito");
        jPanel1.add(BtnNotaDebito);

        BtnConfiguracion.setText("Configuración");
        BtnConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfiguracionActionPerformed(evt);
            }
        });
        jPanel1.add(BtnConfiguracion);

        spPrincipal.setTopComponent(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout destokpLayout = new javax.swing.GroupLayout(destokp);
        destokp.setLayout(destokpLayout);
        destokpLayout.setHorizontalGroup(
            destokpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );
        destokpLayout.setVerticalGroup(
            destokpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        jPanel2.add(destokp, java.awt.BorderLayout.CENTER);

        spPrincipal.setRightComponent(jPanel2);

        getContentPane().add(spPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturaActionPerformed
        // TODO add your handling code here:
        if (iFactura == null || iFactura.isClosed()) {
            iFactura = new IFactura();
            destokp.add(iFactura);
        } else {
            try {
                iFactura.setMaximum(true);
            } catch (PropertyVetoException ex) {
                iFactura = null;
                Logger.getLogger(Documentos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        restaurarVentana(iFactura);
    }//GEN-LAST:event_btnFacturaActionPerformed

    private void btnGuiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiasActionPerformed
        if (iGuia == null || iGuia.isClosed()) {
            iGuia = new IGuiaRemision();
            destokp.add(iGuia);
        } else {
            try {
                iGuia.setMaximum(true);
            } catch (PropertyVetoException ex) {
                iGuia = null;
                Logger.getLogger(Documentos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        restaurarVentana(iGuia);
    }//GEN-LAST:event_btnGuiasActionPerformed

    private void BtnConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfiguracionActionPerformed
        final DLocker bloqueador = new DLocker();
        Thread hilo = new Thread() {
            @Override
            public void run() {
                try {
                    configuracion();
                } finally {
                    bloqueador.dispose();
                }
            }
        };
        hilo.start();
        bloqueador.setVisible(true);
    }//GEN-LAST:event_BtnConfiguracionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Documentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Documentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Documentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Documentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Documentos().setVisible(true);
            }
        });
    }

    private void restaurarVentana(JInternalFrame internalFrame) {
        try {
            if (internalFrame != null) {
                internalFrame.setVisible(true);
                internalFrame.setMaximum(true);
            }
        } catch (Exception ex) {
            Logger.getLogger(Documentos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void configuracion() {
        if(iconfiguracion == null || iconfiguracion.isClosed()){
            iconfiguracion =  new Iconfiguracion();
            destokp.add(iconfiguracion);
        } else {
            try {
                iconfiguracion.setMaximum(true);
            } catch (PropertyVetoException ex) {
                iconfiguracion = null;
                Logger.getLogger(Documentos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        restaurarVentana(iconfiguracion);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConfiguracion;
    private javax.swing.JButton BtnNotaCredito;
    private javax.swing.JButton BtnNotaDebito;
    private javax.swing.JButton btnFactura;
    private javax.swing.JButton btnGuias;
    private javax.swing.JDesktopPane destokp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane spPrincipal;
    // End of variables declaration//GEN-END:variables
}
