/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ec.mirian.internalFrame;

import com.ec.mirian.domain.Configuracion;
import com.ec.mirian.gui.jframe.DLocker;
import com.ec.mirian.service.ConexionService;
import com.ec.mirian.service.FactoryService;
import com.ec.mirian.util.Constante;
import com.ec.mirian.util.Util;

/**
 *
 * @author MARCELO
 */
public class Iconfiguracion extends javax.swing.JInternalFrame {
    
    private static Iconfiguracion INSTANCE;

    /**
     * Creates new form Iconfiguracion
     */
    public Iconfiguracion() {
        INSTANCE = this;
        initComponents();
        cargarConfiguracion();
    }
    
    public static Iconfiguracion getInstance() {
        return INSTANCE;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        pnlConfiguracion = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtFirma = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtXsdFactura = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtXsdNotaCredito = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        txtXsdNotaDebito = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        txtXsdGuia = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        txtXsdRetencion = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        rbtProduccion = new javax.swing.JRadioButton();
        rbtDesarrollo = new javax.swing.JRadioButton();
        jPanel12 = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setMaximizable(true);
        setTitle(".:: CONFIGURACION ::.");
        getContentPane().setLayout(new java.awt.GridLayout());

        pnlConfiguracion.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Firma Electrónica"));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel10.setText("  Ruta Firma:");
        jPanel2.add(jLabel10);

        txtFirma.setEditable(false);
        txtFirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirmaActionPerformed(evt);
            }
        });
        jPanel2.add(txtFirma);

        jLabel16.setText("  Clave:");
        jPanel2.add(jLabel16);

        txtClave.setEditable(false);
        jPanel2.add(txtClave);

        pnlConfiguracion.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Archivos XSD"));
        jPanel1.setLayout(new java.awt.GridLayout(7, 0, 0, 3));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Factura"));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        txtXsdFactura.setEditable(false);
        jPanel3.add(txtXsdFactura);

        jPanel1.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Nota Credito"));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        txtXsdNotaCredito.setEditable(false);
        jPanel4.add(txtXsdNotaCredito);

        jPanel1.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Nota Debito"));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        txtXsdNotaDebito.setEditable(false);
        jPanel5.add(txtXsdNotaDebito);

        jPanel1.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Guia de Remisión"));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        txtXsdGuia.setEditable(false);
        jPanel6.add(txtXsdGuia);

        jPanel1.add(jPanel6);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Comprobante Retención"));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        txtXsdRetencion.setEditable(false);
        jPanel8.add(txtXsdRetencion);

        jPanel1.add(jPanel8);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Ambiente"));
        jPanel9.setLayout(new java.awt.GridLayout());

        rbtProduccion.setText("Producción");
        rbtProduccion.setEnabled(false);
        rbtProduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtProduccionActionPerformed(evt);
            }
        });
        jPanel9.add(rbtProduccion);

        rbtDesarrollo.setSelected(true);
        rbtDesarrollo.setText("Desarrollo");
        rbtDesarrollo.setEnabled(false);
        rbtDesarrollo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtDesarrolloActionPerformed(evt);
            }
        });
        jPanel9.add(rbtDesarrollo);

        jPanel1.add(jPanel9);

        jPanel12.setLayout(new java.awt.GridLayout());

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel12.add(btnEditar);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel12.add(btnGuardar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel12.add(btnCancelar);

        jPanel1.add(jPanel12);

        pnlConfiguracion.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlConfiguracion);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirmaActionPerformed

    private void rbtProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtProduccionActionPerformed
        // TODO add your handling code here:
        rbtDesarrollo.setSelected(false);
        rbtProduccion.setSelected(true);
    }//GEN-LAST:event_rbtProduccionActionPerformed

    private void rbtDesarrolloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtDesarrolloActionPerformed
        // TODO add your handling code here:
        rbtDesarrollo.setSelected(true);
        rbtProduccion.setSelected(false);
    }//GEN-LAST:event_rbtDesarrolloActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        setEditableTxt(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        final DLocker bloqueador = new DLocker();
        Thread hilo = new Thread() {
            @Override
            public void run() {
                try {
                    actualizarConfiguracion();
                } finally {
                    bloqueador.dispose();
                }
            }
        };
        hilo.start();
        bloqueador.setVisible(true);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        setEditableTxt(false);
    }//GEN-LAST:event_btnCancelarActionPerformed
    
    private Configuracion getConfiguracion() {
        ConexionService cs = FactoryService.createConexionService();
        return cs.getConfiguracionById(Constante.ID_CONFIGURACION_DEFECTO);
    }
    
    private void cargarConfiguracion() {
        config = getConfiguracion();
        setTextConfiguracion(config);
        if (config.getAmbiente() == 1) {
            rbtDesarrollo.setSelected(true);
            rbtProduccion.setSelected(false);
        } else {
            rbtProduccion.setSelected(true);
            rbtDesarrollo.setSelected(false);
        }
    }
    
    private void setEditableTxt(boolean b) {
        txtXsdFactura.setEditable(b);
        txtFirma.setEditable(b);
        txtXsdNotaCredito.setEditable(b);
        txtXsdNotaDebito.setEditable(b);
        txtXsdGuia.setEditable(b);
        txtXsdRetencion.setEditable(b);
        txtClave.setEditable(b);

        rbtDesarrollo.setEnabled(b);
        rbtProduccion.setEnabled(b);
    }
    
    private void setTextConfiguracion(Configuracion config) {
        Util.setText(txtFirma, config.getFirma());
        Util.setText(txtXsdFactura, config.getXsdfactura());
        Util.setText(txtXsdNotaCredito, config.getXsdnotacredito());
        Util.setText(txtXsdNotaDebito, config.getXsdnotadebito());
        Util.setText(txtXsdGuia, config.getXsdguia());
        Util.setText(txtXsdRetencion, config.getXsdretencion());
        Util.setText(txtClave, config.getClaveFirma());
    }
    
    private void actualizarConfiguracion() {
        ConexionService cs = FactoryService.createConexionService();
        config.setFirma(Util.getText(txtFirma));
        config.setXsdfactura(Util.getText(txtXsdFactura));
        config.setXsdnotacredito(Util.getText(txtXsdNotaCredito));
        config.setXsdnotadebito(Util.getText(txtXsdNotaDebito));
        config.setXsdguia(Util.getText(txtXsdGuia));
        config.setXsdretencion(Util.getText(txtXsdRetencion));
        config.setClaveFirma(Util.getText(txtClave));
        config.setAmbiente(getAmbiente());
        cs.actualizaConfiguracion(config);
        Util.mostrarExisto("Se Actualizo Correctamente!!!");
    }
    
    private Integer getAmbiente() {
        return rbtDesarrollo.isSelected() ? 1 : 2;
    }

    private Configuracion config;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel pnlConfiguracion;
    private javax.swing.JRadioButton rbtDesarrollo;
    private javax.swing.JRadioButton rbtProduccion;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtFirma;
    private javax.swing.JTextField txtXsdFactura;
    private javax.swing.JTextField txtXsdGuia;
    private javax.swing.JTextField txtXsdNotaCredito;
    private javax.swing.JTextField txtXsdNotaDebito;
    private javax.swing.JTextField txtXsdRetencion;
    // End of variables declaration//GEN-END:variables
}
